# Generated by Django 3.2.4 on 2021-06-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congratulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-published'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['author', 'title'], 'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AlterField(
            model_name='order',
            name='congratulation',
            field=models.TextField(blank=True, null=True, verbose_name='Текст поздравления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Текст поздравления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='song',
            field=models.ForeignKey(on_delete=models.SET('SONG DELETED'), to='congratulation.song', verbose_name='Песня'),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Автор'),
        ),
    ]
